In [19]:
try:
    import numpy as np
    print("Successfully imported numpy! (Version {})".format(np.version.version))
except ImportError:
    print("Could not import numpy!")

def h1(inputs):
    return np.mod(inputs, [9.,9.,9.,9.,9.,9.])

def h2(inputs):
    return np.divide(inputs, 3.)

def h3(inputs):
    return np.dot(inputs, 0) + 2.

def calculateSumOfError(d, y):
    return np.sum((d-y)**2.)

    
X= [1.,3.,6.,10.,11.,13.]    
d= [1.,0.,5.,2. ,1. ,4. ]    

h1_y = h1(X)
h2_y = h2(X)
h3_y = h3(X)
print("{}".format(h1_y))
print("{}".format(h2_y))
print("{}".format(h3_y))

print("{}".format(calculateSumOfError(d, h1_y)))
print("{}".format(calculateSumOfError(d, h2_y)))
print("{}".format(calculateSumOfError(d, h3_y)))




Successfully imported numpy! (Version 1.10.4)
[ 1.  3.  6.  1.  2.  4.]
[ 0.33333333  1.          2.          3.33333333  3.66666667  4.33333333]
[ 2.  2.  2.  2.  2.  2.]
12.0
19.4444444444
19.0
